In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


In [3]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector=torch.tensor([2,2])
vector

tensor([2, 2])

In [7]:
vector.shape
vector.ndim

1

In [8]:
#matrix
MATRIX=torch.tensor([[7,8],
                     [9,10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape
MATRIX[1]

tensor([ 9, 10])

In [11]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

In [12]:
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0])

3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])


**Random Tensor**

In [13]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.0730, 0.1041, 0.7188, 0.9925],
        [0.2315, 0.1529, 0.2388, 0.1515],
        [0.0479, 0.3738, 0.7231, 0.7784]])

In [14]:
random_tensor=torch.rand(10,10,10)

In [15]:
random_image_tensor=torch.rand(size=(224,224,3))
random_image_tensor.shape,random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [16]:
random_image_tensor=torch.rand(size=(3,224,224))
random_image_tensor.shape,random_image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [17]:
random_tensor=torch.rand(size=(3,3))
zeros=torch.zeros(size=(3,3))
zeros * random_tensor
ones=torch.ones(size=(3,3))

In [18]:
ones.dtype

torch.float32

In [19]:
## Creating range of tensor USE arange as deprecated
torch.range(0,10)

<ipython-input-19-cdf98c5af353>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
one_to_ten= torch.arange(1,11)

In [21]:
A=torch.arange(start=0,end=10,step=1)
A

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
#create Tensor Like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Dealing with DataTypes

In [23]:
float_32_tensor=torch.tensor([3.0,4.0,9.0],
                              dtype=None)
float_32_tensor.dtype #Default

torch.float32

In [24]:
float_16_tensor=torch.tensor([3.0,4.0,9.0],
                              dtype=torch.float16)
float_16_tensor.dtype 

torch.float16

In [25]:
A=torch.tensor([3.0,4.0,9.0],
               dtype=None,
               device="cpu",# or "cuda",#which devices on which tensor preseny
               requires_grad=False)#whether or not track gradients on this device
               
A

tensor([3., 4., 9.])

In [26]:
#Convert into another data type
B=A.type(torch.float16)
B

tensor([3., 4., 9.], dtype=torch.float16)

In [27]:
A * B

tensor([ 9., 16., 81.])

In [28]:
print(f"Datatype of tensor : {A.dtype}")
print(f"Size of tensor : {A.size}")
print(f"Shape of tensor : {A.shape}")
print(f"Device on which tensor exists : {A.device}")

Datatype of tensor : torch.float32
Size of tensor : <built-in method size of Tensor object at 0x7fb3d0658400>
Shape of tensor : torch.Size([3])
Device on which tensor exists : cpu


# Manipulating Tensors

In [29]:
# addition,subtraction,multiplication,division
x = torch.tensor([1,2,3])
print(x+10)
print(x*10)
print(x/10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [30]:
#Tensor Inbuilt function
Y= torch.mul(x,10)
print(Y)
Z= torch.add(x,20)
print(Z)

tensor([10, 20, 30])
tensor([21, 22, 23])


In [31]:
#  Multiplication- elementwise or Matrix multiplication (dot prodcut)
print(A*A) # element wise
#or
print(A,"*",A) # element wise
print(f"Equals: {A*A}")
torch.matmul(A,A)# Matrix Multiplication
A@A# Matrix Multiplication


tensor([ 9., 16., 81.])
tensor([3., 4., 9.]) * tensor([3., 4., 9.])
Equals: tensor([ 9., 16., 81.])


tensor(106.)

In [32]:
%%time
torch.matmul(A,A)# Matrix Multiplication

CPU times: user 46 µs, sys: 11 µs, total: 57 µs
Wall time: 63.9 µs


tensor(106.)

In [33]:
%%time
value=0
for i in range(len(A)):
  value+=A[i]*A[i]
print(value)

tensor(106.)
CPU times: user 1.89 ms, sys: 0 ns, total: 1.89 ms
Wall time: 1.92 ms


**Shape Error**

In [34]:
torch.matmul(torch.rand(3,2),torch.rand(3,2)) #error

RuntimeError: ignored

In [35]:
torch.matmul(torch.rand(3,2),torch.rand(2,2))

tensor([[0.1382, 0.4152],
        [0.0205, 0.2049],
        [0.0965, 0.2633]])

In [36]:
torch.rand(3,2)@torch.rand(2,2)

tensor([[0.2711, 0.0725],
        [0.5978, 0.2265],
        [1.4183, 0.4756]])

More to Shape error

In [37]:
# Shapes for Matrix multiplication'
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])
tensor_B=torch.tensor([[7,10],
                      [3,4],
                      [5,6]])
torch.mm(tensor_A,tensor_B) #error

RuntimeError: ignored

In [38]:
torch.mm(tensor_A,tensor_B.T) # No error as transpose is used

tensor([[27, 11, 17],
        [61, 25, 39],
        [95, 39, 61]])

In [39]:
tensor_B.T.shape

torch.Size([2, 3])

## Find the mean max and sum of tensor (Tensor aggregation)

In [40]:
x=torch.arange(0,100,10)
print(torch.max(x))
print(torch.min(x))
print(torch.sum(x))

tensor(90)
tensor(0)
tensor(450)


In [41]:
print(torch.mean(x)) #Error

RuntimeError: ignored

In [42]:
print(torch.mean(x.type(torch.float32)))
#or
print(x.type(torch.float32).mean())

tensor(45.)
tensor(45.)


**Finding the position of min and max**

In [43]:
x=torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [44]:
x.argmin()

tensor(0)

In [45]:
x.argmax()

tensor(9)

# **Reshaping, Stacking, Squeezing,view,Unsqueezing and Permute**
1.  **View** - Return a view of an input tensor of certain shape but keep the same memory as the manin tensor
2.    **Stacking** - Combine Multiple tenosr on top of each other  (vstack) or  side by side (hstack)
3.  **Squeeze** - Removes all 1 dimensions from a tensor
4.  **Unsqueeze** - Add a one dimensions to tensor
5.  **Permute** - Return a view of the input with dimensions permuted or swapped in a certain way









In [46]:
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [47]:
# Add an extra dimensions
x_reshape=x.reshape(9,1)
x_reshape,x_reshape.size

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 <function Tensor.size>)

In [48]:
# Add an extra dimensions
x_reshape=x.reshape(3,3)
x_reshape,x_reshape.size

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 <function Tensor.size>)

In [49]:
# change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [50]:
# Changing z changes x as both share same memory
z[:,0]=5
x,z

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [51]:
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [52]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [61]:
# Torch.squeeze Remove 1 dimensions
x_reshape=x_reshape.reshape(1,9)
x_reshape,x_reshape.shape,x_reshape.squeeze()

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [62]:
x_squeezed=x_reshape.squeeze()

In [59]:
x_reshape.squeeze().shape

torch.Size([9])

In [66]:
# unsequeeze Add Extra  dimension
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
x_unsqueezed,x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
# unsequeeze Add Extra  dimension
x_unsqueezed1=x_squeezed.unsqueeze(dim=1)
x_unsqueezed1,x_unsqueezed1.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [69]:
#Permute
x_original=torch.rand(2,3,5)
x.size()

torch.Size([2, 3, 5])

In [72]:
x_original=torch.rand(size=(224,224,3)) #[height,width,channels]
x_original.size()
# permute to rearrange the axis
x_permuted=x_original.permute(2,0,1)#shifts 0 ->1 ,1->2,2->0
x_permuted.size(),x_original.size()

(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

In [74]:
x_original[0,0,0]=879
x_original[0,0,0],x_permuted[0,0,0]# same memory as view

(tensor(879.), tensor(879.))

# **Indexing Selecting data from tensors**
Same as Numpy

In [76]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [77]:
x[0] #inside first bracket

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [78]:
x[0][0] #dim=1

tensor([1, 2, 3])

In [79]:
x[0][0][0] #last dimension

tensor(1)

In [ ]:
x[1][1][1] # Error

In [81]:
x[0][1][1]

tensor(5)

In [82]:
x[:,0]

tensor([[1, 2, 3]])

In [83]:
x[:,:,1]

tensor([[2, 5, 8]])

In [85]:
# Get all value of zero dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1],x[0,1,1]

(tensor([5]), tensor(5))

In [86]:
x[0,0,:]

tensor([1, 2, 3])

In [89]:
#index to return 9
print(x[0,2,2])
print(x[0][2][2])



# index to retrn 3,6 and 9
print(x[0,:,2])
print(x[:,:,2])
print(x[0,:,2].shape)
print(x[:,:,2].shape)

tensor(9)
tensor(9)
tensor([3, 6, 9])
tensor([[3, 6, 9]])
torch.Size([3])
torch.Size([1, 3])


# **Pytorch and Numpy**


*  Data in numpy want in pytorch torch.from_numpy(ndarray)
*   Data in torch want in Numpy torch.Tensor.numpy()




In [97]:
# Pytorch and numpy
import numpy as np
array=np.arange(1.0,8.0) # Dfault Datatype Float64
tensor=torch.from_numpy(array)
array,array.dtype,tensor,tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 torch.float64)

In [ ]:
import numpy as np
array=np.arange(1.0,8.0) # Dfault Datatype Float64
tensor=torch.from_numpy(array,dtype=torch.float32)# Error
array,array.dtype,tensor,tensor.dtype

In [94]:
import numpy as np
array=np.arange(1.0,8.0) # Dfault Datatype Float64
tensor=torch.from_numpy(array).type(torch.float32) # No error
array,array.dtype,tensor,tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [98]:
# change the value of array
import numpy as np
array=np.arange(1.0,8.0) # Dfault Datatype Float64
array=array+1
array,array.dtype,tensor,tensor.dtype

(array([2., 3., 4., 5., 6., 7., 8.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 torch.float64)

In [99]:
# Tensor to Numpy Array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [100]:
tensor=torch.ones(7)
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))