# Reproducibility (trying to take random out of random)

In [4]:
import torch
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.8708, 0.4196, 0.1955, 0.2360],
        [0.6267, 0.6481, 0.7624, 0.9207],
        [0.7392, 0.3772, 0.1011, 0.0071]])
tensor([[0.8774, 0.2265, 0.1448, 0.0155],
        [0.1693, 0.9440, 0.1993, 0.0399],
        [0.6766, 0.8035, 0.8440, 0.9679]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [5]:
import torch
# Set the random seed
Random_seed = 42
torch.manual_seed(Random_seed)
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [6]:
import torch
# Set the random seed
Random_seed = 42
torch.manual_seed(Random_seed)
random_tensor_A=torch.rand(3,4)
torch.manual_seed(Random_seed)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [8]:
import torch
# Set the random seed
torch.manual_seed(42)
random_tensor_A=torch.rand(3,4)
torch.manual_seed(42)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and Pytorch Objects on GPU for faster computations

In [2]:
### Getting a GPU use tim Dettmers
# Use google colab, AWS,AZURE
!nvidia-smi

Sun Apr 23 09:40:10 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
### Check for GPU access for Pytorch
import torch
torch.cuda.is_available()

True

In [4]:
# Set up device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
torch.cuda.device_count()

1

In [6]:
## Putting Tenosrs and models on GPU for faster computations
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)


tensor([1, 2, 3]) cpu


In [7]:
# Move tensor on GPU
tensor_on_gpu=tensor.to(device)
print(tensor_on_gpu,tensor.device)

tensor([1, 2, 3], device='cuda:0') cpu


### Move tensor back to CPU
#If tensor on GPU , we can not transform it to Numpy
# put Sensor back to CPU and then transorm to Numpy

In [ ]:
tensor_on_gpu.numpy() # error

In [12]:
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
print(tensor_back_on_cpu)

[1 2 3]


Excercises and **Extracurriculam**
https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [13]:
import torch
torch.__version__

'2.0.0+cu118'